import { Card } from "../../types/cardShow";
import data from "../../types/data";
import Urls from "../../components/Homi/Urls";
import { Tmovie } from "../../types/TypeMovieCard";
import { TTv } from "../../types/TypeTVCard";

type urlS = {
    urlTopedMovies: string;
};

type elementData = Omit<data, 'results'> & {
    results: Card[]
}

const { urlTopedMovies }: urlS = Urls();

// Página 1: IDs 101 a 120
const tabMockPage1: elementData = {
    page: 1,
    total_pages: 50,
    total_results: 1000,
    results: [
        { id: 101, title: "O Senhor dos Anéis", name: "O Senhor dos Anéis", poster_path: "/img1.jpg", popularity: 95, release_date: "2001-12-19" },
        { id: 102, title: "Breaking Bad", name: "Breaking Bad", poster_path: "/img2.jpg", popularity: 88, release_date: "2008-01-20" },
        { id: 103, title: "Interestelar", name: "Interestelar", poster_path: "/img3.jpg", popularity: 92, release_date: "2014-11-05" },
        { id: 104, title: "Stranger Things", name: "Stranger Things", poster_path: "/img4.jpg", popularity: 85, release_date: "2016-07-15" },
        { id: 105, title: "Batman: O Cavaleiro das Trevas", name: "Batman: O Cavaleiro das Trevas", poster_path: "/img5.jpg", popularity: 98, release_date: "2008-07-16" },
        { id: 106, title: "The Last of Us", name: "The Last of Us", poster_path: "/img6.jpg", popularity: 91, release_date: "2023-01-15" },
        { id: 107, title: "A Origem", name: "A Origem", poster_path: "/img7.jpg", popularity: 89, release_date: "2010-07-16" },
        { id: 108, title: "Succession", name: "Succession", poster_path: "/img8.jpg", popularity: 78, release_date: "2018-06-03" },
        { id: 109, title: "Pulp Fiction", name: "Pulp Fiction", poster_path: "/img9.jpg", popularity: 87, release_date: "1994-10-14" },
        { id: 110, title: "The Bear", name: "The Bear", poster_path: "/img10.jpg", popularity: 82, release_date: "2022-06-23" },
        { id: 111, title: "Matrix", name: "Matrix", poster_path: "/img11.jpg", popularity: 90, release_date: "1999-03-31" },
        { id: 112, title: "O Poderoso Chefão", name: "O Poderoso Chefão", poster_path: "/img12.jpg", popularity: 99, release_date: "1972-03-14" },
        { id: 113, title: "Forrest Gump", name: "Forrest Gump", poster_path: "/img13.jpg", popularity: 88, release_date: "1994-07-06" },
        { id: 114, title: "The Crown", name: "The Crown", poster_path: "/img14.jpg", popularity: 84, release_date: "2016-11-04" },
        { id: 115, title: "The Office", name: "The Office", poster_path: "/img15.jpg", popularity: 95, release_date: "2005-03-24" },
        { id: 116, title: "Gladiador", name: "Gladiador", poster_path: "/img16.jpg", popularity: 89, release_date: "2000-05-01" },
        { id: 117, title: "Avatar", name: "Avatar", poster_path: "/img17.jpg", popularity: 86, release_date: "2009-12-18" },
        { id: 118, title: "The Mandalorian", name: "The Mandalorian", poster_path: "/img18.jpg", popularity: 91, release_date: "2019-11-12" },
        { id: 119, title: "Severance", name: "Severance", poster_path: "/img19.jpg", popularity: 83, release_date: "2022-02-18" },
        { id: 120, title: "Chernobyl", name: "Chernobyl", poster_path: "/img20.jpg", popularity: 96, release_date: "2019-05-06" }
    ]
};

// Página 2: IDs 201 a 220
const tabMockPage2: elementData = {
    page: 2,
    total_pages: 50,
    total_results: 1000,
    results: [
        { id: 201, title: "Clube da Luta", name: "Clube da Luta", poster_path: "/img21.jpg", popularity: 94, release_date: "1999-10-15" },
        { id: 202, title: "Better Call Saul", name: "Better Call Saul", poster_path: "/img22.jpg", popularity: 84, release_date: "2015-02-08" },
        { id: 203, title: "Parasita", name: "Parasita", poster_path: "/img23.jpg", popularity: 90, release_date: "2019-05-30" },
        { id: 204, title: "The Boys", name: "The Boys", poster_path: "/img24.jpg", popularity: 88, release_date: "2019-07-26" },
        { id: 205, title: "Duna: Parte Dois", name: "Duna: Parte Dois", poster_path: "/img25.jpg", popularity: 97, release_date: "2024-02-27" },
        { id: 206, title: "Round 6", name: "Round 6", poster_path: "/img26.jpg", popularity: 81, release_date: "2021-09-17" },
        { id: 207, title: "Oppenheimer", name: "Oppenheimer", poster_path: "/img27.jpg", popularity: 96, release_date: "2023-07-19" },
        { id: 208, title: "Dark", name: "Dark", poster_path: "/img28.jpg", popularity: 79, release_date: "2017-12-01" },
        { id: 209, title: "Spider-Man: Across the Spider-Verse", name: "Spider-Man: Across the Spider-Verse", poster_path: "/img29.jpg", popularity: 93, release_date: "2023-05-31" },
        { id: 210, title: "O Show de Truman", name: "O Show de Truman", poster_path: "/img30.jpg", popularity: 87, release_date: "1998-06-05" },
        { id: 211, title: "Coringa", name: "Coringa", poster_path: "/img31.jpg", popularity: 91, release_date: "2019-10-02" },
        { id: 212, title: "A Lista de Schindler", name: "A Lista de Schindler", poster_path: "/img32.jpg", popularity: 95, release_date: "1993-11-30" },
        { id: 213, title: "Shrek", name: "Shrek", poster_path: "/img33.jpg", popularity: 85, release_date: "2001-05-18" },
        { id: 214, title: "The Witcher", name: "The Witcher", poster_path: "/img34.jpg", popularity: 82, release_date: "2019-12-20" },
        { id: 215, title: "Ted Lasso", name: "Ted Lasso", poster_path: "/img35.jpg", popularity: 88, release_date: "2020-08-14" },
        { id: 216, title: "Whiplash", name: "Whiplash", poster_path: "/img36.jpg", popularity: 92, release_date: "2014-10-10" },
        { id: 217, title: "Toy Story", name: "Toy Story", poster_path: "/img37.jpg", popularity: 89, release_date: "1995-11-22" },
        { id: 218, title: "Black Mirror", name: "Black Mirror", poster_path: "/img38.jpg", popularity: 86, release_date: "2011-12-04" },
        { id: 219, title: "Bacurau", name: "Bacurau", poster_path: "/img39.jpg", popularity: 77, release_date: "2019-08-29" },
        { id: 220, title: "The White Lotus", name: "The White Lotus", poster_path: "/img40.jpg", popularity: 80, release_date: "2021-07-11" }
    ]
};

// Página 3: IDs 301 a 320 (gerados dinamicamente para brevidade)
const tabMockPage3: elementData = {
    page: 3,
    total_pages: 50,
    total_results: 1000,
    results: Array.from({ length: 20 }, (_, i) => ({
        id: 301 + i,
        title: `Filme Página 3 - Item ${i + 1}`,
        name: `Filme Página 3 - Item ${i + 1}`,
        poster_path: `/img3-${i}.jpg`,
        popularity: 70 + i,
        release_date: "2022-01-01"
    }))
};

// --- MOCK MESTRE: Contém tudo ---
const mockFetchedData: elementData = {
    page: 1,
    total_pages: 50,
    total_results: 1000,
    results: [
        ...tabMockPage1.results,
        ...tabMockPage2.results,
        ...tabMockPage3.results
    ]
};

const MovieMockData: Tmovie[] = [
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "The Godfather",
        title: "O Poderoso Chefão",
        tagline: "Uma oferta que você não poderá recusar.",
        overview: "O patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.",
        runtime: 175,
        poster_path: "/3bhkrj0W9XpS7pYpS69iMbiO938.jpg",
        budget: 6000000,
        revenue: 245066411,
        popularity: 87.5,
        release_date: "1972-03-14"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "The Matrix",
        title: "Matrix",
        tagline: "Bem-vindo ao mundo real.",
        overview: "Um hacker descobre que a realidade é uma simulação criada por máquinas e se junta a uma rebelião.",
        runtime: 136,
        poster_path: "/f89U3YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 63000000,
        revenue: 463517383,
        popularity: 92.3,
        release_date: "1999-03-31"
    },
    {
        origin_country: ["KR"],
        original_language: "ko",
        original_title: "Gisaengchung",
        title: "Parasita",
        tagline: "Ato de bravura.",
        overview: "Toda a família de Ki-taek está desempregada e vive em um porão sujo. Por obra do acaso, o filho começa a dar aulas de inglês para a filha de uma família rica.",
        runtime: 132,
        poster_path: "/77139YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 11400000,
        revenue: 258700000,
        popularity: 90.1,
        release_date: "2019-05-30"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Interstellar",
        title: "Interestelar",
        tagline: "O próximo passo da humanidade será o maior.",
        overview: "As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem populações mundiais.",
        runtime: 169,
        poster_path: "/gEU2QniE6E77NI6vCU6m9iBPfDc.jpg",
        budget: 165000000,
        revenue: 677471339,
        popularity: 95.8,
        release_date: "2014-11-05"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Avatar: The Way of Water",
        title: "Avatar: O Caminho da Água",
        tagline: "Retorne a Pandora.",
        overview: "Jake Sully vive com sua nova família no planeta Pandora. Uma ameaça familiar retorna para terminar o que foi começado anteriormente.",
        runtime: 192,
        poster_path: "/t68239YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 350000000,
        revenue: 2320250281,
        popularity: 98.2,
        release_date: "2022-12-14"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Joker",
        title: "Coringa",
        tagline: "Coloque um rosto feliz.",
        overview: "Isolado, intimidado e desconsiderado pela sociedade, o fracassado comediante Arthur Fleck inicia um movimento contra a elite de Gotham City.",
        runtime: 122,
        poster_path: "/ud339YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 55000000,
        revenue: 1074251311,
        popularity: 89.4,
        release_date: "2019-10-02"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "The Dark Knight",
        title: "Batman: O Cavaleiro das Trevas",
        tagline: "Bem-vindo a um mundo sem regras.",
        overview: "Com a ajuda de Jim Gordon e Harvey Dent, Batman mantém a ordem em Gotham até que um jovem criminoso conhecido como Coringa apareça.",
        runtime: 152,
        poster_path: "/qJ2tW6WMUDp9QjVvMv2aXGYSfS6.jpg",
        budget: 185000000,
        revenue: 1004558444,
        popularity: 97.1,
        release_date: "2008-07-16"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Everything Everywhere All at Once",
        title: "Tudo em Todo Lugar ao Mesmo Tempo",
        tagline: "Uma imigrante chinesa é arrastada para uma aventura insana.",
        overview: "Uma ruptura interdimensional bagunça a realidade e uma inesperada heroína precisa canalizar seus novos poderes para lutar contra perigos bizarros do multiverso.",
        runtime: 139,
        poster_path: "/w3439YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 14300000,
        revenue: 141200000,
        popularity: 86.7,
        release_date: "2022-03-24"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Inception",
        title: "A Origem",
        tagline: "Sua mente é o cenário do crime.",
        overview: "Um ladrão que rouba segredos corporativos através do uso de tecnologia de compartilhamento de sonhos é encarregado da tarefa inversa: plantar uma ideia.",
        runtime: 148,
        poster_path: "/9e3tm61Ho7r9pS69iMbiO9384pE.jpg",
        budget: 160000000,
        revenue: 825532764,
        popularity: 91.5,
        release_date: "2010-07-15"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Oppenheimer",
        title: "Oppenheimer",
        tagline: "O mundo mudará para sempre.",
        overview: "O físico J. Robert Oppenheimer trabalha com uma equipe de cientistas durante o Projeto Manhattan, levando ao desenvolvimento da bomba atômica.",
        runtime: 180,
        poster_path: "/80239YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 100000000,
        revenue: 960000000,
        popularity: 96.8,
        release_date: "2023-07-19"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Pulp Fiction",
        title: "Pulp Fiction: Tempo de Violência",
        tagline: "Você não vai saber os fatos até ver a ficção.",
        overview: "As vidas de dois assassinos, um boxeador, a esposa de um gângster e dois bandidos se entrelaçam em quatro histórias de violência e redenção.",
        runtime: 154,
        poster_path: "/f6874N4S69iMbiO9384pE9e3tY9.jpg",
        budget: 8000000,
        revenue: 213928762,
        popularity: 88.2,
        release_date: "1994-09-10"
    },
    {
        origin_country: ["BR"],
        original_language: "pt",
        original_title: "Cidade de Deus",
        title: "Cidade de Deus",
        tagline: "Se correr o bicho pega, se ficar o bicho come.",
        overview: "Nas favelas do Rio de Janeiro, dois rapazes seguem caminhos diferentes: um se torna fotógrafo e o outro um traficante de armas.",
        runtime: 130,
        poster_path: "/k9939YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 3300000,
        revenue: 30641770,
        popularity: 85.9,
        release_date: "2002-08-30"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Fight Club",
        title: "Clube da Luta",
        tagline: "Mischief. Mayhem. Soap.",
        overview: "Um homem insone e um vendedor de sabão criam um clube de luta clandestino que evolui para algo muito maior.",
        runtime: 139,
        poster_path: "/b9639YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 63000000,
        revenue: 100853753,
        popularity: 93.7,
        release_date: "1999-10-15"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "The Whale",
        title: "A Baleia",
        tagline: "Não há como escapar de si mesmo.",
        overview: "Um professor de inglês recluso que vive com obesidade severa tenta se reconectar com sua filha adolescente afastada.",
        runtime: 117,
        poster_path: "/j1239YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 3000000,
        revenue: 54883205,
        popularity: 82.1,
        release_date: "2022-12-09"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Spider-Man: Across the Spider-Verse",
        title: "Homem-Aranha: Através do Aranhaverso",
        tagline: "Com grande poder vem grande responsabilidade.",
        overview: "Miles Morales retorna para o próximo capítulo da saga do Aranhaverso, uma aventura épica que transportará o Homem-Aranha através do multiverso.",
        runtime: 140,
        poster_path: "/x0039YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 100000000,
        revenue: 690516673,
        popularity: 94.5,
        release_date: "2023-05-31"
    },
    {
        origin_country: ["JP"],
        original_language: "ja",
        original_title: "Sen to Chihiro no Kamikakushi",
        title: "A Viagem de Chihiro",
        tagline: "Nada do que acontece é esquecido, mesmo que você não consiga se lembrar.",
        overview: "Durante a mudança de sua família para o subúrbio, uma garota de 10 anos vagueia por um mundo governado por deuses, bruxas e espíritos.",
        runtime: 125,
        poster_path: "/y4439YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 19000000,
        revenue: 355473394,
        popularity: 89.9,
        release_date: "2001-07-20"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "The Shawshank Redemption",
        title: "Um Sonho de Liberdade",
        tagline: "O medo pode manter você prisioneiro. A esperança pode libertar você.",
        overview: "Dois homens presos tornam-se amigos ao longo de muitos anos, encontrando consolo e eventual redenção através de atos de decência comum.",
        runtime: 142,
        poster_path: "/z5539YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 25000000,
        revenue: 28341469,
        popularity: 91.2,
        release_date: "1994-09-22"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Dune: Part Two",
        title: "Duna: Parte Dois",
        tagline: "Vida longa aos guerreiros.",
        overview: "Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família.",
        runtime: 167,
        poster_path: "/cz139YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 190000000,
        revenue: 711844358,
        popularity: 97.8,
        release_date: "2024-02-27"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "Gladiator",
        title: "Gladiador",
        tagline: "O que fazemos em vida ecoa na eternidade.",
        overview: "Um ex-general romano busca vingança contra o imperador corrupto que assassinou sua família e o enviou para a escravidão.",
        runtime: 155,
        poster_path: "/v9939YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 103000000,
        revenue: 465348545,
        popularity: 88.7,
        release_date: "2000-05-01"
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_title: "The Lion King",
        title: "O Rei Leão",
        tagline: "O Rei de todos os filmes.",
        overview: "Um jovem príncipe leão foge do seu reino apenas para aprender o verdadeiro significado de responsabilidade e bravura.",
        runtime: 88,
        poster_path: "/s1139YpS69iMbiO9384pE9e3tY9.jpg",
        budget: 45000000,
        revenue: 968483777,
        popularity: 90.4,
        release_date: "1994-06-23"
    }]
const TvMockData: TTv[] = [
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "Breaking Bad",
        name: "Breaking Bad: A Química do Mal",
        tagline: "Cuidado com quem você pisa.",
        overview: "Um professor de química do ensino médio diagnosticado com câncer de pulmão inoperável volta-se para a fabricação e venda de metanfetamina para garantir o futuro de sua família.",
        episode_run_time: [47],
        poster_path: "/ggm8JNNoFEpW37v8AnYfX89O96O.jpg",
        popularity: 98.5,
        first_air_date: "2008-01-20",
        last_air_date: "2013-09-29",
        number_of_episodes: 62,
        number_of_seasons: 5,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "Stranger Things",
        name: "Stranger Things",
        tagline: "Um verão pode mudar tudo.",
        overview: "Quando um garoto desaparece, uma pequena cidade descobre um mistério envolvendo experimentos secretos, forças sobrenaturais aterrorizantes e uma estranha garotinha.",
        episode_run_time: [50],
        poster_path: "/x2LSRm21uTEx2Pq2S5uR7iG7XSB.jpg",
        popularity: 92.4,
        first_air_date: "2016-07-15",
        last_air_date: "2022-07-01",
        number_of_episodes: 34,
        number_of_seasons: 4,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Last of Us",
        name: "The Last of Us",
        tagline: "Quando você estiver perdido na escuridão, procure a luz.",
        overview: "Vinte anos após a civilização moderna ter sido destruída, Joel é contratado para tirar Ellie de uma zona de quarentena opressiva.",
        episode_run_time: [59],
        poster_path: "/uKvH561NEwhu39R2Br6pZ6uC19u.jpg",
        popularity: 94.1,
        first_air_date: "2023-01-15",
        last_air_date: "2023-03-12",
        number_of_episodes: 9,
        number_of_seasons: 1,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Black Mirror",
        name: "Black Mirror",
        tagline: "O futuro é brilhante?",
        overview: "Uma série de antologia que explora um mundo de alta tecnologia próximo, onde as maiores inovações da humanidade e os instintos mais sombrios colidem.",
        episode_run_time: [60],
        poster_path: "/79939YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 85.7,
        first_air_date: "2011-12-04",
        last_air_date: "2023-06-15",
        number_of_episodes: 27,
        number_of_seasons: 6,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["DE"],
        original_language: "de",
        original_name: "Dark",
        name: "Dark",
        tagline: "Tudo está conectado.",
        overview: "O desaparecimento de duas crianças pequenas em uma cidade alemã expõe as relações duplas entre quatro famílias.",
        episode_run_time: [60],
        poster_path: "/w4439YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 81.3,
        first_air_date: "2017-12-01",
        last_air_date: "2020-06-27",
        number_of_episodes: 26,
        number_of_seasons: 3,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "Succession",
        name: "Succession",
        tagline: "Lute pelo que é seu.",
        overview: "Acompanhe a família Roy enquanto eles contemplam o futuro de seu império mediático quando o patriarca começa a se afastar da empresa.",
        episode_run_time: [60],
        poster_path: "/7Y96m99YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 88.2,
        first_air_date: "2018-06-03",
        last_air_date: "2023-05-28",
        number_of_episodes: 40,
        number_of_seasons: 4,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Bear",
        name: "O Urso",
        tagline: "Cada segundo conta.",
        overview: "Um jovem chef do mundo da alta gastronomia volta para Chicago para administrar a lanchonete de sua família.",
        episode_run_time: [30],
        poster_path: "/uS8239YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 91.5,
        first_air_date: "2022-06-23",
        last_air_date: "2024-06-26",
        number_of_episodes: 28,
        number_of_seasons: 3,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Boys",
        name: "The Boys",
        tagline: "Nunca encontre seus heróis.",
        overview: "Um grupo de vigilantes se propõe a derrubar super-heróis corruptos que abusam de seus superpoderes.",
        episode_run_time: [60],
        poster_path: "/m9239YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 96.4,
        first_air_date: "2019-07-26",
        last_air_date: "2024-07-18",
        number_of_episodes: 32,
        number_of_seasons: 4,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["KR"],
        original_language: "ko",
        original_name: "Ojing-eo Geim",
        name: "Round 6",
        tagline: "45,6 bilhões de wons é um jogo de criança.",
        overview: "Centenas de jogadores sem dinheiro aceitam um convite estranho para competir em jogos infantis. Lá dentro, um prêmio tentador aguarda.",
        episode_run_time: [55],
        poster_path: "/s8839YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 89.9,
        first_air_date: "2021-09-17",
        last_air_date: "2021-09-17",
        number_of_episodes: 9,
        number_of_seasons: 1,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "Severance",
        name: "Ruptura",
        tagline: "Você é o que você faz?",
        overview: "Mark lidera uma equipe de funcionários cujas memórias foram cirurgicamente divididas entre sua vida profissional e pessoal.",
        episode_run_time: [45],
        poster_path: "/k1139YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 82.6,
        first_air_date: "2022-02-18",
        last_air_date: "2022-04-08",
        number_of_episodes: 9,
        number_of_seasons: 1,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["ES"],
        original_language: "es",
        original_name: "La Casa de Papel",
        name: "La Casa de Papel",
        tagline: "O maior roubo da história.",
        overview: "Oito ladrões fazem reféns e se fecham na Casa da Moeda da Espanha, enquanto um gênio do crime manipula a polícia.",
        episode_run_time: [50],
        poster_path: "/x7739YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 87.1,
        first_air_date: "2017-05-02",
        last_air_date: "2021-12-03",
        number_of_episodes: 41,
        number_of_seasons: 5,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Office",
        name: "The Office (US)",
        tagline: "Um documentário sobre o local de trabalho.",
        overview: "O cotidiano hilário e muitas vezes desconfortável dos funcionários de uma empresa de papel em Scranton.",
        episode_run_time: [22],
        poster_path: "/p0039YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 95.2,
        first_air_date: "2005-03-24",
        last_air_date: "2013-05-16",
        number_of_episodes: 188,
        number_of_seasons: 9,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "Better Call Saul",
        name: "Better Call Saul",
        tagline: "S'all good, man!",
        overview: "A metamorfose do advogado iniciante Jimmy McGill no carismático e inescrupuloso Saul Goodman.",
        episode_run_time: [46],
        poster_path: "/v5439YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 89.3,
        first_air_date: "2015-02-08",
        last_air_date: "2022-08-15",
        number_of_episodes: 63,
        number_of_seasons: 6,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Mandalorian",
        name: "O Mandaloriano",
        tagline: "Este é o caminho.",
        overview: "As viagens de um caçador de recompensas solitário nos confins da galáxia, longe da autoridade da Nova República.",
        episode_run_time: [40],
        poster_path: "/m1139YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 91.8,
        first_air_date: "2019-11-12",
        last_air_date: "2023-04-19",
        number_of_episodes: 24,
        number_of_seasons: 3,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Crown",
        name: "The Crown",
        tagline: "O dever chama.",
        overview: "Esta série dramática segue a política, rivalidades e relacionamentos da Rainha Elizabeth II e os eventos que fizeram a história.",
        episode_run_time: [58],
        poster_path: "/c9939YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 84.5,
        first_air_date: "2016-11-04",
        last_air_date: "2023-12-14",
        number_of_episodes: 60,
        number_of_seasons: 6,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "Game of Thrones",
        name: "A Guerra dos Tronos",
        tagline: "O inverno está chegando.",
        overview: "Várias famílias nobres lutam pelo controle das terras de Westeros, enquanto uma força antiga retorna após milênios.",
        episode_run_time: [60],
        poster_path: "/u2239YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 97.6,
        first_air_date: "2011-04-17",
        last_air_date: "2019-05-19",
        number_of_episodes: 73,
        number_of_seasons: 8,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Chernobyl",
        name: "Chernobyl",
        tagline: "Qual é o custo das mentiras?",
        overview: "A história real da explosão de 1986 na Usina Nuclear de Chernobyl e os esforços heróicos para salvar a Europa.",
        episode_run_time: [60],
        poster_path: "/h8839YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 86.4,
        first_air_date: "2019-05-06",
        last_air_date: "2019-06-03",
        number_of_episodes: 5,
        number_of_seasons: 1,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "Arcane",
        name: "Arcane",
        tagline: "Cada lenda tem um começo.",
        overview: "Em meio ao conflito entre as cidades de Piltover e Zaun, duas irmãs lutam em lados opostos de uma guerra de tecnologias e crenças.",
        episode_run_time: [40],
        poster_path: "/a1139YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 93.9,
        first_air_date: "2021-11-06",
        last_air_date: "2021-11-20",
        number_of_episodes: 9,
        number_of_seasons: 1,
        status: "Returning Series",
        in_production: true
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "Ted Lasso",
        name: "Ted Lasso",
        tagline: "Acredite.",
        overview: "Um treinador de futebol americano é contratado para treinar um time de futebol inglês, apesar de não ter nenhuma experiência no esporte.",
        episode_run_time: [30],
        poster_path: "/t0039YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 88.7,
        first_air_date: "2020-08-14",
        last_air_date: "2023-05-31",
        number_of_episodes: 34,
        number_of_seasons: 3,
        status: "Ended",
        in_production: false
    },
    {
        origin_country: ["US"],
        original_language: "en",
        original_name: "The White Lotus",
        name: "The White Lotus",
        tagline: "O paraíso tem um preço.",
        overview: "As aventuras de vários funcionários e hóspedes em um resort exclusivo em uma semana que mudará suas vidas.",
        episode_run_time: [60],
        poster_path: "/w5539YpS69iMbiO9384pE9e3tY9.jpg",
        popularity: 83.2,
        first_air_date: "2021-07-11",
        last_air_date: "2022-12-11",
        number_of_episodes: 13,
        number_of_seasons: 2,
        status: "Returning Series",
        in_production: true
    }
]

export { urlTopedMovies, mockFetchedData, MovieMockData, TvMockData, tabMockPage1, tabMockPage2, tabMockPage3 }

